apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJkb2NrZXIucGtnLmdpdGh1Yi5jb20iOiB7CgkJCSJhdXRoIjogImEyMXpNekV6T2pObE4yVTBZbVl4TjJJM1ptUmxZakExWVRVd1pUZzRaRGMyT0RBNE9EaGlZVGxtWlRGbU1UST0iCgkJfQoJfSwKCSJIdHRwSGVhZGVycyI6IHsKCQkiVXNlci1BZ2VudCI6ICJEb2NrZXItQ2xpZW50LzE5LjAzLjggKGxpbnV4KSIKCX0KfQo=
kind: Secret
metadata:
  name: kinx-cloud-controller-image-secret
  namespace: kube-system
type: kubernetes.io/dockerconfigjson
